### ISSUE TITLE
Create Merchants tab and link market tab to Nycoinmarket.com

### ISSUE THREAD

**Issue by NYCoinNova** [NewYorkCoin-NYC/NYC-site#23]
Can we create a merchants tab or "nyc accepted here" tab that links to nycoinstores.com.

This will keep all merchants in one organized space, allowing them to create wallets online and accept payments on the website once we get updated.
Nycoinstores.com is going to get emails from future merchants and verify before adding them to the site. On going we will provide continued support to the merchants that join our community.

Market link should be self explanatory. 

Thanks

**Comment by nicovs** [comment]
#19

**Comment by ltanyc** [comment]
nycoinstores.com has been linked
