### ISSUE TITLE
Change point 6 in FAQ - Link it directly to merchant site

### ISSUE THREAD

**Issue by cryptonyx2** [NewYorkCoin-NYC/NYC-site#25]
Point 6 in FAQ currently shows this: 
What merchants currently accept NYCoin:
(a) in New York, 3 merchants with two more in talks; (b) one merchant in Vermont; (c) one merchant in Florida; and (d) one merchant in Pennsylvania. Please visit the website for more merchant acceptance information.

Should just link it to the merchants site so we don't have to update it everytime we get new merchants on board

**Comment by cryptonyx2** [comment]
https://nycoin.community/faq.html

**Comment by ltanyc** [comment]
done
