### ISSUE TITLE
Add exchanges 

### ISSUE THREAD

**Issue by NewYorkCoinFan** [NewYorkCoin-NYC/NYC-site#48]
2 exchanges missing on the website
- https://octaex.com/trade/index/market/nyc_eth
- https://nibyx.com/

Link to logos
- Nibyx png: https://ip.bitcointalk.org/?u=http%3A%2F%2Fi.imgur.com%2FnG1I2Fs.png&t=588&c=qvkiVolozPPEzQ
- Octaex png: https://rise.vision/wp-content/uploads/2018/04/octaex-1.png
- Graviex png: https://neetcoin.jp/openai/exchange_graviex/logo-graviex-300x80.png

**Comment by jamesburrell2** [comment]
Need to also add

-https://exrates.me
Link to logo

- https://exrates.me/client/img/Logo_blue.png
@nicovs 

I'm not sure about NiByx - it doesn't seem like that exchange is fully functional.

**Comment by nicovs** [comment]
#54
